version: "3.8"

# environment
x-env-db: &db-env
  POSTGRES_DB: "blog"
  POSTGRES_PASSWORD: "blog-password"
  POSTGRES_USER: "blog-user"

x-env-app: &app-env
  ALLOWED_HOSTS: "*"
  DEBUG: "True"
  DJANGO_SETTINGS_MODULE: "blog.development"
  SECRET_KEY: "fb7edcb5d081b23d07ec7bb64c59ffe0e0c793109ec8a55583beb064eb274fb9"

  <<: *db-env

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PACKAGE_TYPE: -dev
    container_name: django_blog_api
    image: nayanbiswas/django_blog:latest
    restart: unless-stopped
    command: python ./app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      <<: *app-env
    # env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - django_blog-backend-tier

  db:
    image: postgres:16
    container_name: django_blog_db
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - django_blog-backend-tier
    volumes:
      - django_blog-db:/var/lib/postgresql/data
    environment:
      <<: *db-env

volumes:
  django_blog-db:
    driver: local

networks:
  django_blog-backend-tier:
    driver: bridge
