# Generated by Django 4.2.6 on 2023-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("short_description", models.CharField(blank=True)),
                ("cover_image", models.FilePathField()),
                ("description", models.TextField()),
                ("total_comment", models.PositiveIntegerField(default=0)),
                ("total_reaction", models.PositiveIntegerField(default=0)),
                ("publish_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
