# Generated by Django 4.2.6 on 2023-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="posts"),
        ),
    ]
