# Generated by Django 4.2.6 on 2023-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_reaction_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-id"]},
        ),
    ]
